# Generated by Django 3.1.4 on 2021-01-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cerveza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('alcohol', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mililitros', models.IntegerField()),
                ('artesanal', models.BooleanField()),
                ('nacionalidad', models.CharField(blank=True, max_length=255, null=True)),
                ('creado', models.DateTimeField(auto_now=True)),
                ('editado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
